- set_fact:
    pkg_use_aur: "{{ pkg_aur_name != 'none' }}"
    pkg_use_apt: "{{ pkg_apt_name != 'none' }}"

- debug:
    msg:
    - "Package Install Vars"
    - "pkg_name: '{{ pkg_name }}'"
    - "pkg_aur_name: '{{ pkg_aur_name }}' (use: {{ pkg_use_aur }})"
    - "pkg_aur_builder: '{{ pkg_aur_builder }}'"
    verbosity: 1

- name: pacman - install packages
  pacman:
    name: "{{ pkg_name }}"
    state: present
  when:
  - ansible_distribution in pacman_distros
  - (not pkg_use_aur|bool) or pkg_install_both

- name: aur - install packages
  aur:
    name: "{{ item }}"
    use: "{{ pkg_aur_builder }}"
    skip_installed: true
  with_items: "{{ pkg_aur_name }}"
  become: true
  become_user: "{{ pkg_aur_user }}"
  when:
  - ansible_distribution in pacman_distros
  - pkg_use_aur|bool
  environment:
    PATH: "{{ pkg_aur_path }}"

- name: apt - install packages
  apt:
    name: "{{ pkg_apt_name }}"
    state: present
  when:
  - ansible_distribution in apt_distros
  - pkg_use_apt|bool

- name: package - install packages
  package:
    name: "{{ pkg_name }}"
    state: present
  when:
  - ansible_distribution in apt_distros
  - ansible_distribution not in pacman_distros
  - not pkg_use_apt|bool
